# -*- coding: utf-8 -*-
"""GoggleTrends_sports_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11v2DzNnGsccOTKaVeM5QVKpGu0FW7gsp
"""

!pip install pytrends pandas matplotlib

from pytrends.request import TrendReq
import pandas as pd
import matplotlib.pyplot as plt

pytrends = TrendReq(hl='en-US', tz=360)
keyword = ['Indian Premier League']
timeframe = '2008-01-01 2025-12-31'

pytrends.build_payload(keyword, cat=0, timeframe=timeframe, geo='', gprop='')
interest_over_time_df = pytrends.interest_over_time()
interest_over_time_df.to_csv('Sports_IPL_trends_2008_2025.csv')